FROM phusion/baseimage
MAINTAINER Michał Piotrowski <michal.piotrowski@erlang-solutions.com>

COPY ./member/clusterize /clusterize
COPY ./member/start.sh /start.sh
COPY ./member/mongooseim.tar.gz mongooseim.tar.gz
VOLUME ["/member", "/var/lib/mongooseim"]

EXPOSE 4369 5222 5269 5280 9100

ENTRYPOINT ["/start.sh"]
