#!/bin/bash

node=$1
ip=$(docker inspect mongo-1 | grep "IPAddress" | tail -n 1 | cut -d '"' -f 4)
confdir=$(docker inspect mongo-1 | grep ":/member" | cut -d ":" -f 1 | tr '"' ' ')
conffile="${confdir}ejabberd.cfg"
if [ -f $conffile ]; then
    port=$(grep ejabberd_c2s config/ejabberd.cfg | head -n 1 | sed -e 's/\([^0-9]*\)\(.*\)/\2/' | sed -e 's/\([0-9]*\).*/\1/')
else
    port=5222
fi

echo "Mongoose node: $node, $ip:$port"
telnet $ip $port
